using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.OData;
using Microsoft.AspNetCore.OData.Batch;
using Microsoft.AspNetCore.OData.Formatter.Serialization;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OData.Edm;
using Microsoft.OData.ModelBuilder;
using Microsoft.OData.UriParser;
using Newtonsoft.Json.Serialization;

namespace ODataCoreTest
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(op => op.AllowEmptyInputInBodyModelBinding = true);

            services.AddAuthentication("EagleODataAuthentication").AddScheme<AuthenticationSchemeOptions, EagleODataAuthenticationHandler>("EagleODataAuthentication", null);
            services.AddScoped<EagleODataAuthenticationService>();

            var mvcBuilder = services.AddMvc(options => { options.EnableEndpointRouting = false; }).AddNewtonsoftJson(op => op.SerializerSettings.ContractResolver = new DefaultContractResolver());
            var edmModel = GetEdmModel();

            mvcBuilder.AddOData(opt =>
            {
                opt.AddModel("{contextToken}", edmModel, configureAction =>
                {
                    configureAction.AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(ODataBatchHandler), s => new MyODataBatchHandler());
                    configureAction.AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(ODataSerializerProvider), sp => new MyODataSerializerProvider(sp));
                });
                opt.Filter().Select().Expand().SetMaxTop(null).Count().OrderBy();
            });
        }

        public static IEdmModel GetEdmModel()
        {
            var odataBuilder = new ODataConventionModelBuilder() { Namespace = "Model.Entities", ContainerName = "DefaultContainer" };
            odataBuilder.EntitySet<Student0>("Student0");
            odataBuilder.EntityType<Student0>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student1>("Student1");
            odataBuilder.EntityType<Student1>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student2>("Student2");
            odataBuilder.EntityType<Student2>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student3>("Student3");
            odataBuilder.EntityType<Student3>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student4>("Student4");
            odataBuilder.EntityType<Student4>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student5>("Student5");
            odataBuilder.EntityType<Student5>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student6>("Student6");
            odataBuilder.EntityType<Student6>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student7>("Student7");
            odataBuilder.EntityType<Student7>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student8>("Student8");
            odataBuilder.EntityType<Student8>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student9>("Student9");
            odataBuilder.EntityType<Student9>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student10>("Student10");
            odataBuilder.EntityType<Student10>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student11>("Student11");
            odataBuilder.EntityType<Student11>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student12>("Student12");
            odataBuilder.EntityType<Student12>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student13>("Student13");
            odataBuilder.EntityType<Student13>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student14>("Student14");
            odataBuilder.EntityType<Student14>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student15>("Student15");
            odataBuilder.EntityType<Student15>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student16>("Student16");
            odataBuilder.EntityType<Student16>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student17>("Student17");
            odataBuilder.EntityType<Student17>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student18>("Student18");
            odataBuilder.EntityType<Student18>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student19>("Student19");
            odataBuilder.EntityType<Student19>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student20>("Student20");
            odataBuilder.EntityType<Student20>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student21>("Student21");
            odataBuilder.EntityType<Student21>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student22>("Student22");
            odataBuilder.EntityType<Student22>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student23>("Student23");
            odataBuilder.EntityType<Student23>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student24>("Student24");
            odataBuilder.EntityType<Student24>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student25>("Student25");
            odataBuilder.EntityType<Student25>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student26>("Student26");
            odataBuilder.EntityType<Student26>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student27>("Student27");
            odataBuilder.EntityType<Student27>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student28>("Student28");
            odataBuilder.EntityType<Student28>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student29>("Student29");
            odataBuilder.EntityType<Student29>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student30>("Student30");
            odataBuilder.EntityType<Student30>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student31>("Student31");
            odataBuilder.EntityType<Student31>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student32>("Student32");
            odataBuilder.EntityType<Student32>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student33>("Student33");
            odataBuilder.EntityType<Student33>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student34>("Student34");
            odataBuilder.EntityType<Student34>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student35>("Student35");
            odataBuilder.EntityType<Student35>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student36>("Student36");
            odataBuilder.EntityType<Student36>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student37>("Student37");
            odataBuilder.EntityType<Student37>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student38>("Student38");
            odataBuilder.EntityType<Student38>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student39>("Student39");
            odataBuilder.EntityType<Student39>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student40>("Student40");
            odataBuilder.EntityType<Student40>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student41>("Student41");
            odataBuilder.EntityType<Student41>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student42>("Student42");
            odataBuilder.EntityType<Student42>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student43>("Student43");
            odataBuilder.EntityType<Student43>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student44>("Student44");
            odataBuilder.EntityType<Student44>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student45>("Student45");
            odataBuilder.EntityType<Student45>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student46>("Student46");
            odataBuilder.EntityType<Student46>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student47>("Student47");
            odataBuilder.EntityType<Student47>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student48>("Student48");
            odataBuilder.EntityType<Student48>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student49>("Student49");
            odataBuilder.EntityType<Student49>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student50>("Student50");
            odataBuilder.EntityType<Student50>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student51>("Student51");
            odataBuilder.EntityType<Student51>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student52>("Student52");
            odataBuilder.EntityType<Student52>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student53>("Student53");
            odataBuilder.EntityType<Student53>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student54>("Student54");
            odataBuilder.EntityType<Student54>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student55>("Student55");
            odataBuilder.EntityType<Student55>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student56>("Student56");
            odataBuilder.EntityType<Student56>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student57>("Student57");
            odataBuilder.EntityType<Student57>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student58>("Student58");
            odataBuilder.EntityType<Student58>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student59>("Student59");
            odataBuilder.EntityType<Student59>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student60>("Student60");
            odataBuilder.EntityType<Student60>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student61>("Student61");
            odataBuilder.EntityType<Student61>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student62>("Student62");
            odataBuilder.EntityType<Student62>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student63>("Student63");
            odataBuilder.EntityType<Student63>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student64>("Student64");
            odataBuilder.EntityType<Student64>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student65>("Student65");
            odataBuilder.EntityType<Student65>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student66>("Student66");
            odataBuilder.EntityType<Student66>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student67>("Student67");
            odataBuilder.EntityType<Student67>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student68>("Student68");
            odataBuilder.EntityType<Student68>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student69>("Student69");
            odataBuilder.EntityType<Student69>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student70>("Student70");
            odataBuilder.EntityType<Student70>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student71>("Student71");
            odataBuilder.EntityType<Student71>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student72>("Student72");
            odataBuilder.EntityType<Student72>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student73>("Student73");
            odataBuilder.EntityType<Student73>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student74>("Student74");
            odataBuilder.EntityType<Student74>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student75>("Student75");
            odataBuilder.EntityType<Student75>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student76>("Student76");
            odataBuilder.EntityType<Student76>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student77>("Student77");
            odataBuilder.EntityType<Student77>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student78>("Student78");
            odataBuilder.EntityType<Student78>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student79>("Student79");
            odataBuilder.EntityType<Student79>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student80>("Student80");
            odataBuilder.EntityType<Student80>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student81>("Student81");
            odataBuilder.EntityType<Student81>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student82>("Student82");
            odataBuilder.EntityType<Student82>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student83>("Student83");
            odataBuilder.EntityType<Student83>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student84>("Student84");
            odataBuilder.EntityType<Student84>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student85>("Student85");
            odataBuilder.EntityType<Student85>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student86>("Student86");
            odataBuilder.EntityType<Student86>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student87>("Student87");
            odataBuilder.EntityType<Student87>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student88>("Student88");
            odataBuilder.EntityType<Student88>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student89>("Student89");
            odataBuilder.EntityType<Student89>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student90>("Student90");
            odataBuilder.EntityType<Student90>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student91>("Student91");
            odataBuilder.EntityType<Student91>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student92>("Student92");
            odataBuilder.EntityType<Student92>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student93>("Student93");
            odataBuilder.EntityType<Student93>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student94>("Student94");
            odataBuilder.EntityType<Student94>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student95>("Student95");
            odataBuilder.EntityType<Student95>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student96>("Student96");
            odataBuilder.EntityType<Student96>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student97>("Student97");
            odataBuilder.EntityType<Student97>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student98>("Student98");
            odataBuilder.EntityType<Student98>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student99>("Student99");
            odataBuilder.EntityType<Student99>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student100>("Student100");
            odataBuilder.EntityType<Student100>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student101>("Student101");
            odataBuilder.EntityType<Student101>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student102>("Student102");
            odataBuilder.EntityType<Student102>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student103>("Student103");
            odataBuilder.EntityType<Student103>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student104>("Student104");
            odataBuilder.EntityType<Student104>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student105>("Student105");
            odataBuilder.EntityType<Student105>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student106>("Student106");
            odataBuilder.EntityType<Student106>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student107>("Student107");
            odataBuilder.EntityType<Student107>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student108>("Student108");
            odataBuilder.EntityType<Student108>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student109>("Student109");
            odataBuilder.EntityType<Student109>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student110>("Student110");
            odataBuilder.EntityType<Student110>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student111>("Student111");
            odataBuilder.EntityType<Student111>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student112>("Student112");
            odataBuilder.EntityType<Student112>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student113>("Student113");
            odataBuilder.EntityType<Student113>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student114>("Student114");
            odataBuilder.EntityType<Student114>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student115>("Student115");
            odataBuilder.EntityType<Student115>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student116>("Student116");
            odataBuilder.EntityType<Student116>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student117>("Student117");
            odataBuilder.EntityType<Student117>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student118>("Student118");
            odataBuilder.EntityType<Student118>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student119>("Student119");
            odataBuilder.EntityType<Student119>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student120>("Student120");
            odataBuilder.EntityType<Student120>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student121>("Student121");
            odataBuilder.EntityType<Student121>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student122>("Student122");
            odataBuilder.EntityType<Student122>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student123>("Student123");
            odataBuilder.EntityType<Student123>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student124>("Student124");
            odataBuilder.EntityType<Student124>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student125>("Student125");
            odataBuilder.EntityType<Student125>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student126>("Student126");
            odataBuilder.EntityType<Student126>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student127>("Student127");
            odataBuilder.EntityType<Student127>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student128>("Student128");
            odataBuilder.EntityType<Student128>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student129>("Student129");
            odataBuilder.EntityType<Student129>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student130>("Student130");
            odataBuilder.EntityType<Student130>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student131>("Student131");
            odataBuilder.EntityType<Student131>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student132>("Student132");
            odataBuilder.EntityType<Student132>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student133>("Student133");
            odataBuilder.EntityType<Student133>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student134>("Student134");
            odataBuilder.EntityType<Student134>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student135>("Student135");
            odataBuilder.EntityType<Student135>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student136>("Student136");
            odataBuilder.EntityType<Student136>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student137>("Student137");
            odataBuilder.EntityType<Student137>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student138>("Student138");
            odataBuilder.EntityType<Student138>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student139>("Student139");
            odataBuilder.EntityType<Student139>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student140>("Student140");
            odataBuilder.EntityType<Student140>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student141>("Student141");
            odataBuilder.EntityType<Student141>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student142>("Student142");
            odataBuilder.EntityType<Student142>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student143>("Student143");
            odataBuilder.EntityType<Student143>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student144>("Student144");
            odataBuilder.EntityType<Student144>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student145>("Student145");
            odataBuilder.EntityType<Student145>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student146>("Student146");
            odataBuilder.EntityType<Student146>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student147>("Student147");
            odataBuilder.EntityType<Student147>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student148>("Student148");
            odataBuilder.EntityType<Student148>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student149>("Student149");
            odataBuilder.EntityType<Student149>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student150>("Student150");
            odataBuilder.EntityType<Student150>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student151>("Student151");
            odataBuilder.EntityType<Student151>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student152>("Student152");
            odataBuilder.EntityType<Student152>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student153>("Student153");
            odataBuilder.EntityType<Student153>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student154>("Student154");
            odataBuilder.EntityType<Student154>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student155>("Student155");
            odataBuilder.EntityType<Student155>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student156>("Student156");
            odataBuilder.EntityType<Student156>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student157>("Student157");
            odataBuilder.EntityType<Student157>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student158>("Student158");
            odataBuilder.EntityType<Student158>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student159>("Student159");
            odataBuilder.EntityType<Student159>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student160>("Student160");
            odataBuilder.EntityType<Student160>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student161>("Student161");
            odataBuilder.EntityType<Student161>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student162>("Student162");
            odataBuilder.EntityType<Student162>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student163>("Student163");
            odataBuilder.EntityType<Student163>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student164>("Student164");
            odataBuilder.EntityType<Student164>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student165>("Student165");
            odataBuilder.EntityType<Student165>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student166>("Student166");
            odataBuilder.EntityType<Student166>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student167>("Student167");
            odataBuilder.EntityType<Student167>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student168>("Student168");
            odataBuilder.EntityType<Student168>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student169>("Student169");
            odataBuilder.EntityType<Student169>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student170>("Student170");
            odataBuilder.EntityType<Student170>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student171>("Student171");
            odataBuilder.EntityType<Student171>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student172>("Student172");
            odataBuilder.EntityType<Student172>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student173>("Student173");
            odataBuilder.EntityType<Student173>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student174>("Student174");
            odataBuilder.EntityType<Student174>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student175>("Student175");
            odataBuilder.EntityType<Student175>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student176>("Student176");
            odataBuilder.EntityType<Student176>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student177>("Student177");
            odataBuilder.EntityType<Student177>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student178>("Student178");
            odataBuilder.EntityType<Student178>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student179>("Student179");
            odataBuilder.EntityType<Student179>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student180>("Student180");
            odataBuilder.EntityType<Student180>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student181>("Student181");
            odataBuilder.EntityType<Student181>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student182>("Student182");
            odataBuilder.EntityType<Student182>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student183>("Student183");
            odataBuilder.EntityType<Student183>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student184>("Student184");
            odataBuilder.EntityType<Student184>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student185>("Student185");
            odataBuilder.EntityType<Student185>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student186>("Student186");
            odataBuilder.EntityType<Student186>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student187>("Student187");
            odataBuilder.EntityType<Student187>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student188>("Student188");
            odataBuilder.EntityType<Student188>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student189>("Student189");
            odataBuilder.EntityType<Student189>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student190>("Student190");
            odataBuilder.EntityType<Student190>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student191>("Student191");
            odataBuilder.EntityType<Student191>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student192>("Student192");
            odataBuilder.EntityType<Student192>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student193>("Student193");
            odataBuilder.EntityType<Student193>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student194>("Student194");
            odataBuilder.EntityType<Student194>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student195>("Student195");
            odataBuilder.EntityType<Student195>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student196>("Student196");
            odataBuilder.EntityType<Student196>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student197>("Student197");
            odataBuilder.EntityType<Student197>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student198>("Student198");
            odataBuilder.EntityType<Student198>().HasKey(s => s.Id);
            odataBuilder.EntitySet<Student199>("Student199");
            odataBuilder.EntityType<Student199>().HasKey(s => s.Id);



            return odataBuilder.GetEdmModel();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder builder, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                builder.UseDeveloperExceptionPage();
            }
            builder.UseODataBatching();
            builder.UseHttpsRedirection();
            builder.UseRouting();
            builder.UseAuthentication();
            builder.UseAuthorization();
            builder.UseEndpoints(routeBuilder =>
            {
                routeBuilder.MapControllers();
            });
        }
    }
}
